version: "3.9"

services:
  librarydb-prod:
    image: postgres:16.3
    container_name: librarydb-prod
    environment:
      POSTGRES_PASSWORD: postgresprod
      POSTGRES_USER: postgresprod
      POSTGRES_DB: library
    ports:
      - "6433:5432"
    networks:
      - library-network
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  library-service:
    build:
      context: ./sblibrary-api
      dockerfile: Dockerfile
    container_name: library-service
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DATASOURCE_URL: "jdbc:postgresql://librarydb-prod:5432/library"
      DATASOURCE_USERNAME: "postgresprod"
      DATASOURCE_PASSWORD: "postgresprod"
      GOOGLE_CLIENT_ID: "client_id"
      GOOGLE_CLIENT_SECRET: "client_secret"
      SPRING_PROFILES_ACTIVE: "production"
      TZ: "America/Sao_Paulo"
    depends_on:
      - librarydb-prod
    networks:
      - library-network

networks:
  library-network:
    external: true

