version: "3.9"

services:
  librarydb-prod:
    image: postgres:16.3
    container_name: librarydb-prod
    environment:
      POSTGRES_PASSWORD: postgresprod
      POSTGRES_USER: postgresprod
      POSTGRES_DB: library
    ports:
      - "6432:5432"
    networks:
      - library-network
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

networks:
  library-network:
    external: true

