
ALTER TABLE author 
ADD COLUMN dt_created TIMESTAMP WITH TIME ZONE DEFAULT now(),
ADD COLUMN dt_updated TIMESTAMP WITH TIME ZONE DEFAULT now();

ALTER TABLE book
ADD COLUMN dt_created TIMESTAMP WITH TIME ZONE DEFAULT now(),
ADD COLUMN dt_updated TIMESTAMP WITH TIME ZONE DEFAULT now();

